### ISSUE TITLE
Models and dataset on Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [microsoft/satclip#2]
Really cool work! To make it a bit easier to find and use the models and dataset I've uploaded copies to the Hub. The model and dataset cards are a work in progress but it might also be nicer to transfer the models and datasets to the [Microsoft organisation](Ihttps://huggingface.co/microsoft) on the Hub. 

The dataset is here: https://huggingface.co/datasets/davanstrien/satclip
The models are split into different repos for each model, for example, here: https://huggingface.co/davanstrien/SatCLIP-ResNet18-L10

Let me know if you'd like me to move them to the Microsoft org?

**Comment by konstantinklemmer** [comment]
Hi! Sure, that would be fantastic, thanks for offering. The repository does have a model card that also includes information about the dataset here: https://github.com/microsoft/satclip/blob/main/MODELCARD.md.

Let me know if you need anything else!

**Comment by konstantinklemmer** [comment]
@davanstrien Closing this issue unless there's anything else (=

**Comment by davanstrien** [comment]
Yes, can close this now. I've moved the models here with your model cards added: https://huggingface.co/microsoft?search_models=satclip. Thanks again for this great work :)

**Comment by konstantinklemmer** [comment]
Awesome, thank you!
