### ISSUE TITLE
[Question] Coordinate Reference System

### ISSUE THREAD

**Issue by jejjohnson** [microsoft/satclip#4]
Hi, 

I was taking a look at the code base and I had a question about the coordinate reference system (CRS) of the original satellite data. As I understand, the Sentinel-2 data has its original CRS and I imagine the lat-lon coordinates are on a curvilinear grid. Are you all doing some sort of interpolation to a rectilinear or regular grid in your preprocessing? Or do you keep everything in its original projection? 

I see immense benefits to keeping it in its original projection because one could potentially lose a lot of information going back and forth between grids with different interpolators, e.g. Curvilinear -> Rectilinear -> Train NN -> Curvilinear.  In addition, it definitely makes sense to avoid this because your architecture features a position encoder for the coordinates. However, I just wanted to check to make sure I am understanding all of the preprocessing involved beforehand.

Thanks!

**Comment by calebrob6** [comment]
Hello @jejjohnson,

Yep -- we keep all imagery patches in their default UTM coordinate system (i.e. we don't reproject or resample to EPSG:4326 or EPSG:3857). SatCLIP does expect lat,lon coordinates in EPSG:4326 as input though.

Does that answer your question?

Best,
Caleb
