### ISSUE TITLE
Population density downstream task dataset

### ISSUE THREAD

**Issue by nsutezo** [microsoft/satclip#6]
hi @konstantinklemmer ,

We are trying to reproduce evaluation on the downstream population density task but couldn't find a notebook on it. Could you kindly clarify, which gridded population data file was used? 

Also found this from the cited MOSAIKS paper in the SatClip Paper: https://github.com/Global-Policy-Lab/mosaiks-paper/blob/master/code/analysis/2_label_creation/population/extractPopulation.R

Thanks :)

**Comment by konstantinklemmer** [comment]
Hi Simone! You can access the data for the population density task (and the other 4 datasets we created; Country, Ecoregions, Biome & Elevation) here: https://drive.google.com/drive/folders/1tI2qo6iioRrv3P1OxSXwHKObpLCrinad?usp=sharing

**Comment by nsutezo** [comment]
Thanks Konsta!

**Comment by konstantinklemmer** [comment]
No problem, happy to help!
